# Generated by Django 3.1.1 on 2021-06-18 15:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HMUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(default='User', max_length=100, verbose_name='username')),
                ('first_name', models.CharField(max_length=100)),
                ('unique_code', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('first_passwd', models.BooleanField(default=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastlogin', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(default='Ghana', max_length=1000)),
                ('hospital', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+233200000000' or '0200000000'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('permission', models.CharField(choices=[('0', 'Dev SuperUser'), ('1', 'HM Admin SuperUser'), ('2', 'HM Administrator'), ('3', 'HM Auditor'), ('4', 'Doctor'), ('5', 'Pharmacy'), ('6', 'Finance'), ('7', 'Residence'), ('8', 'Patient')], default='0', max_length=100)),
                ('lastupdatedtime', models.DateTimeField(blank=True, null=True)),
                ('lastupdatedby_id', models.IntegerField(default=0)),
                ('name_of_client', models.CharField(blank=True, max_length=255, null=True)),
                ('return_message', models.TextField(blank=True, null=True)),
                ('temporal_login_fails', models.IntegerField(default=0)),
                ('permanent_login_fails', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'HM users',
                'verbose_name_plural': 'HM users',
                'ordering': ('id', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355, unique=True, verbose_name='Client Name')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address')),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_edit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=1000, null=True)),
                ('action', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('device', models.CharField(blank=True, max_length=1000, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
                ('longitude', models.CharField(blank=True, max_length=1000, null=True)),
                ('latitude', models.CharField(blank=True, max_length=1000, null=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='myusers.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='EditClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_editing', models.BooleanField(default=False)),
                ('is_edit', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('hmuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myuluser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hmuser',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myusers', to='myusers.client'),
        ),
    ]
